import { test, expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";

test("club types, selection facts, URL and independent saves", async ({ page }, info) => {
  const errors: string[] = [];
  page.on("pageerror", e => errors.push(e.message));
  page.on("console", e => { if (e.type() === "error") errors.push(e.text()); });
  await page.goto("/?view=all");
  await page.getByRole("button", { name: "연합동아리", exact: true }).click();
  await expect(page.locator(".program-card")).toHaveCount(6);
  await page.reload();
  await expect(page.getByRole("button", { name: "연합동아리", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.locator(".cover-link img").evaluateAll(imgs => Promise.all(imgs.map(img => { (img as HTMLImageElement).loading = "eager"; return (img as HTMLImageElement).decode(); })));
  await page.screenshot({ path: `test-results/${info.project.name}-clubs.png`, fullPage: true });
  await page.locator('a.card-title[href="/programs/depromeet"]').click();
  await expect(page.locator(".notice")).toContainText("모집 예정");
  await expect(page.locator(".notice")).toContainText("2026.10.08");
  await expect(page.locator(".selection-process")).toContainText("직무·컬처핏");
  await expect(page.locator(".notice")).toContainText("지원 대상미확인");
  await page.getByRole("button", { name: "프로그램 스크랩", exact: true }).click();
  await page.getByRole("button", { name: "조직 스크랩", exact: true }).click();
  await page.locator(".detail-cover").evaluate((img: HTMLImageElement) => img.decode());
  await page.screenshot({ path: `test-results/${info.project.name}-club-detail.png`, fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  expect((await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa"]).analyze()).violations).toEqual([]);
  await page.reload();
  await expect(page.getByRole("button", { name: "프로그램 스크랩 해제", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(page.getByRole("button", { name: "조직 스크랩 해제", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.goBack();
  await expect(page.locator(".program-card")).toHaveCount(6);
  await page.goto("/?view=saved");
  await expect(page.locator(".program-card")).toHaveCount(1);
  await page.getByRole("button", { name: "프로그램 스크랩 해제", exact: true }).click();
  await page.getByRole("button", { name: "조직 1", exact: true }).click();
  await expect(page.locator(".organization-list article")).toContainText("디프만");
  await page.goto("/programs/mashup");
  await expect(page.locator(".notice")).toHaveCount(0);
  await expect(page.getByText("현재 확인된 모집 공고 없음", { exact: true })).toBeVisible();
  expect(errors).toEqual([]);
});
